### ISSUE TITLE
Can schematic files be open source?

### ISSUE THREAD

**Issue by colinheru** [meijie-jesse/Spark-ESP8266-Smart-Device#1]

**Comment by colinheru** [comment]
Schematic_Spark-ESP8266-Smart-Device_v10.0.pdf, this file is invalid so it cannot be displayed. Thank you very much.

**Comment by meijie-jesse** [comment]
I just checked it, all the files are correct, or you can download it. The Pdf file can be displayed normally.
https://github.com/meijie-jesse/Spark-ESP8266-Smart-Device/blob/master/Schematic_Spark-ESP8266-Smart-Device_v10.0.pdf
